### PR TITLE
log4j2

### PR DESCRIPTION
**Pull request by pwinckles**
This PR is based on @bbpennel's work and:

1. Standardizes to slf4j
2. Uses log4j2 as the backend
3. Adjust the log level of Tika so it's less chatty

### CODE REVIEW

**Comment by pwinckles** [comment]
Resolves https://github.com/harvard-lts/fits/issues/244

**Comment by bbpennel** [comment]
Thanks for bringing this over, @pwinckles

**Comment by bbpennel** [comment]
Was it decided to switch from log4j2 to reload4j? I am noticing that 1.5.3 released with log4j2 but 1.5.4 and 1.5.5 have both removed it in favor of reload4j.

**Comment by daveneiman** [comment]
The 1.5.5 release is solely remediation for log4j replaced with reload4j. It contains none of the work from the Community Sprint since the output of that work has yet to be approved by the directory of Media Preservation Services.

**Comment by bbpennel** [comment]
Okay, thank you for the reply. I was just wondering since log4j2 was in 1.5.3 but not in the following to releases
https://github.com/harvard-lts/fits/blob/1.5.3/pom.xml#L17
It isn't a problem, I was just not sure what the goals for the project were.

**Comment by daveneiman** [comment]
A couple of tools in this version of FITS were still at log4j (1) so upgrading to log4j2 was causing some problems. With the Community Sprint work these tools were updated to the latest which contained log4j2.

**Pull request merged**
