### PR TITLE
Adding new tools to FITS

### PR DESCRIPTION
**Pull request by luis100**
Adding tools to perform characterization of the following file types: plain text, shapefile, rich text file (RTF), Lotus Notes (NSF), Microsoft Office files (word, powerpoint and excel), email (EML), Autocad (DWG), Corel Draw (CDR) and Adobe Illustrator (AI).

Also added support for FIDO, for file format detection (MIME and PRONOM ID).

### CODE REVIEW

**Comment by atz** [comment]
This is an enormous amount of code, now substantially out of date and in conflict.  Any chance of breaking this up into more reviewable chunks?

**Comment by daveneiman** [comment]
There have been substantial and significant architectural changes since this pull request from 2014. Pull requests would need to be against current code. Also, please submit pull requests against the 'dev' branch. Thanks for your understanding. 'master' is strictly for releases.

**Comment by luis100** [comment]
@atz @daveneiman nice to hear from you. This was indeed an huge pull request. The merging was not supposed to be done like this, but the lack of feedback at the time we were developing (2014) gave us no other option.

We are not currently working on this, in fact this approach of adding more tools revealed significant architectural problems in terms of performance, that we had a couple of ideas how to improve but needed a complete overhaul of the system behind fits to achieve it. 

Still, this code might have some interesting new features you could integrate in FITS if you are up to it. For example, feature extraction of Microsoft Office files would probably be of the interest of the community using FITS.

Unfortunately, we cannot spare resources to work on this right now, so is up to you to take what you like or leave it. Cheers.

**Comment by daveneiman** [comment]
Similarly, we currently do not have the resources to look at this pull request especially considering it is against FITS code that has changed considerably.

**Pull request closed without merging**
