### PR TITLE
Integrate cadtool

### PR DESCRIPTION
**Pull request by isaacsimmons**

### CODE REVIEW

**Comment by daveneiman** [comment]
Hi Dave,

Curious what this Closed thing is with your name on it.
In looking at the link below (#44) it's a pull request to the old branch 'tools_upgrade'. Uh oh...I hope I didn't mess up the contractors work.

Thanks,
David

**Comment by isaacsimmons** [comment]
I can re-send the pull request if you've merged "tools_upgrade" into the master branch.

Alternatively, if you're discarding the "tools_upgrade" changes, it wouldn't take much to fix "cadtool_integration" to merge into master instead (I suspect just taking out the classpath-dirs attribute in the <tool> element in fits.xml).

However, when testing, I originally ran into some errors when using the (bouncycastle) pdf encryption library due to incompatible versions between the dependencies of the various tools which I thought "tools_upgrade" was meant to fix.

**Comment by daveneiman** [comment]
Our emails crossed. I think there is no urgency on our end if there's none on yours.

Good to know about the bouncycastle problem in spite of the class loader changes. Definitely something I will look into once I incorporate your work.


Thanks,
David

**Comment by isaacsimmons** [comment]
Yeah, no rush. I'll keep my fork of the repository around in the meantime, just let me know if you want a new pull request and which branch I should target if so. The pull request itself is really pretty minor -- just a handful of new jars for lib/cadtool and one-line edits to a handful of config files.

Also, to be clear, I ran into the class loader issues when testing against the master branch, but didn't have any troubles when using the tools_upgrade branch.

**Pull request closed without merging**
